# Podfile
# Platform minimum for the app
platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'FLUTTER_ROOT=\$(SRCROOT)/Flutter',
        'FLUTTER_APPLICATION_PATH=\$(SRCROOT)/..',
        'FLUTTER_TARGET=\$(SRCROOT)/../lib/main.dart',
        'FLUTTER_BUILD_DIR=build',
        'SYMROOT=\${SOURCE_ROOT}/../build/ios',
        'FLUTTER_BUILD_NAME=1.0.0',
        'FLUTTER_BUILD_NUMBER=1',
        'DART_OBFUSCATION=false',
        'TRACK_WIDGET_CREATION=true',
        'TREE_SHAKE_ICONS=false',
        'PACKAGE_CONFIG=\$(SRCROOT)/../.dart_tool/package_config.json',
      ]
    end
  end
end
